sensor:
  # Published temperature
  - platform: template
    id: skyfandc_temp
    name: "${fan_name} Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 0
    disabled_by_default: true

  # ADC reading
  - platform: adc
    id: skyfandc_temp_voltage
    pin: ${ntc_adc_pin}
    update_interval: never

  # Resistance calculation
  - platform: resistance
    id: skyfandc_temp_resistance
    sensor: skyfandc_temp_voltage
    configuration: DOWNSTREAM
    resistor: 100kOhm
    reference_voltage: 3.3

  # NTC calculation
  - platform: ntc
    id: skyfandc_ntc_temp
    sensor: skyfandc_temp_resistance
    calibration:
      b_constant: 3435
      reference_temperature: 25°C
      reference_resistance: 10kOhm

switch:
  - platform: gpio
    id: skyfandc_ntc_vcc
    pin: ${ntc_vcc_pin}
    restore_mode: ALWAYS_OFF

esphome:
  on_boot:
    priority: -100
    then:
      - switch.turn_on: skyfandc_ntc_vcc
      - component.update: skyfandc_temp_voltage
      - switch.turn_off: skyfandc_ntc_vcc
      - sensor.template.publish:
          id: skyfandc_temp
          state: !lambda "return id(skyfandc_ntc_temp).state;"

interval:
  - interval: 30s
    then:
      - switch.turn_on: skyfandc_ntc_vcc
      - component.update: skyfandc_temp_voltage
      - switch.turn_off: skyfandc_ntc_vcc
      - sensor.template.publish:
          id: skyfandc_temp
          state: !lambda "return id(skyfandc_ntc_temp).state;"