# Estimated light power based on brightness.

sensor:
  - platform: template
    id: skyfandc_light_power
    name: "${light_name} Power"

    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    accuracy_decimals: 1

    update_interval: 30s

    lambda: |-
      if (!id(skyfandc_light).current_values.is_on())
        return 0.0f;

      return id(skyfandc_light).current_values.get_brightness() * ${light_max_power};

    disabled_by_default: true